export const initialSongs = [
  { title: 'Blinding Lights', artist: 'The Weeknd', album: 'After Hours', genre: 'Synthwave' },
  { title: 'Save Your Tears', artist: 'The Weeknd', album: 'After Hours', genre: 'Pop' },
  { title: 'Starboy', artist: 'The Weeknd', album: 'Starboy', genre: 'Pop' },
  { title: 'Shape of You', artist: 'Ed Sheeran', album: '÷ (Divide)', genre: 'Pop' },
  { title: 'Perfect', artist: 'Ed Sheeran', album: '÷ (Divide)', genre: 'Pop' },
  { title: 'Bad Habits', artist: 'Ed Sheeran', album: '= (Equals)', genre: 'Pop' },
  { title: 'Bohemian Rhapsody', artist: 'Queen', album: 'A Night at the Opera', genre: 'Rock' },
  { title: 'Don\'t Stop Me Now', artist: 'Queen', album: 'Jazz', genre: 'Rock' },
  { title: 'Another One Bites the Dust', artist: 'Queen', album: 'The Game', genre: 'Rock' },
  { title: 'Hotel California', artist: 'Eagles', album: 'Hotel California', genre: 'Rock' },
  { title: 'Despacito', artist: 'Luis Fonsi', album: 'Vida', genre: 'Latin' },
  { title: 'Sicko Mode', artist: 'Travis Scott', album: 'Astroworld', genre: 'Hip Hop' },
  { title: 'Goosebumps', artist: 'Travis Scott', album: 'Birds in the Trap', genre: 'Hip Hop' },
  { title: 'HUMBLE.', artist: 'Kendrick Lamar', album: 'DAMN.', genre: 'Hip Hop' },
  { title: 'DNA.', artist: 'Kendrick Lamar', album: 'DAMN.', genre: 'Hip Hop' },
  { title: 'Alright', artist: 'Kendrick Lamar', album: 'To Pimp a Butterfly', genre: 'Hip Hop' },
  { title: 'Fly Me to the Moon', artist: 'Frank Sinatra', album: 'It Might as Well Be Swing', genre: 'Jazz' },
  { title: 'My Way', artist: 'Frank Sinatra', album: 'My Way', genre: 'Jazz' },
  { title: 'Take Five', artist: 'Dave Brubeck', album: 'Time Out', genre: 'Jazz' },
  { title: 'Clair de Lune', artist: 'Claude Debussy', album: 'Suite Bergamasque', genre: 'Classical' },
  { title: 'Strobe', artist: 'deadmau5', album: 'For Lack of a Better Name', genre: 'Electronic' },
  { title: 'One More Time', artist: 'Daft Punk', album: 'Discovery', genre: 'Electronic' },
  { title: 'Get Lucky', artist: 'Daft Punk', album: 'Random Access Memories', genre: 'Electronic' }
];
